---
name: "Eric R. Scott, PhD"
position: "Scientific Programmer & Educator"
address: "University of Arizona"
phone: +1 925-788-9855
www: ericrscott.com
email: ericscott@arizona.edu
github: Aariq
aboutme: ""
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  vitae::moderncv:
    theme: classic
# header-includes:
#   - \definecolor{linkscolor}{HTML}{026dbb}
#   - \hypersetup{colorlinks=true, linkcolor=linkscolor, filecolor=linkscolor, urlcolor=linkscolor, urlbordercolor=linkscolor}
---

Updated `r Sys.Date()`

```{r eval=FALSE, include=FALSE}
# Remember to spell check!!
data_files <- list.files(here("data"), pattern = ".csv", full.names = TRUE)
spelling::spell_check_files(c("CV.Rmd", data_files))
```

```{r eval=FALSE, include=FALSE}
# To update CV on my website, run the following code in the console:
rmarkdown::render(here::here("CV", "CV.Rmd"), output_file = "../../website-quarto/Eric Scott cv.pdf")
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tidyverse)
library(here)
library(glue)
library(conflicted)
conflict_prefer("filter", "dplyr")
conflict_prefer("here", "here")
conflict_prefer("collapse", "glue")
source("../R/zotero_get_pubs.R")
```

```{r experience, inclue=FALSE}
jobs.raw <- read_csv(here::here("data", "jobs.csv"))
jobs <-
  jobs.raw %>% 
  fill(Start, End, What, With, Where, Tag) %>%  
  mutate(Start = mdy(Start),
         End = mdy(End)) %>% 
  mutate(When = case_when(
    is.na(End) ~ glue("{year(Start)}--Present") %>% as.character(),
    year(Start) == year(End) ~ year(End) %>% as.character(),
    TRUE ~ glue("{year(Start)}--{year(End)}") %>% as.character()
  )) %>% 
  mutate(End = if_else(is.na(End), today() + years(2), End)) #if no end date specified, set it to two years from now for sorting purposes, i.e. so jobs I'm still doing show up at top.
```

```{r presentations, include=FALSE}
presentations.raw <- read_csv(here("data", "presentations.csv"))
presentations <- 
  presentations.raw %>% 
  mutate(When = mdy(When)) %>% 
  filter(When > ymd("2008-01-01")) # filter out really old talks
```

```{r prof-devel, include=FALSE}
development.raw <- read_csv(here("data", "professional development.csv"))
development <- 
  development.raw %>% 
  mutate(date = mdy(date))
```

```{r awards, include=FALSE}
awards.raw <- read_csv(here("data", "awards and grants.csv"))
awards <- awards.raw %>% 
  mutate(date = mdy(date)) %>% 
  arrange(desc(date)) %>% 
  filter(date > ymd("2008-01-01")) #filter out undergrad
```

```{r edu, include=FALSE}
edu.raw <- read_csv(here("data", "education.csv"))
edu <-
  edu.raw %>% 
  mutate(pi = if_else(!is.na(pi), glue("PI: {pi}"), as.character(NA)),
         dissertation = glue("\\textbf{[dissertation]}", .open = "[", .close = "]")) %>% 
  gather(dissertation, pi, key = "whytype", value = "why")
edu["why"]
```

```{r outreach, include=FALSE}
outreach.raw <- read_csv(here("data", "outreach.csv"))
outreach <- outreach.raw %>% mutate(sortdate = mdy(sortdate))

```

```{r service, include=FALSE}
reviews.raw <- read_csv(here("data", "reviews.csv"))
reviews <- reviews.raw |> select(Journal, Count)

```


# Education

```{r}
detailed_entries(edu, 
                 when = glue("{start_date}--{end_date}"),
                 what = degree,
                 where = location,
                 with = university,
                 why = why,
                 .protect = FALSE)

```
# Research Experience

```{=html}
<!--
A sentence or two about my research interests
-->
```

```{r research}
jobs %>% 
  filter(Tag == "research") %>% 
  # arrange(desc(Start)) %>%
  arrange(desc(End)) %>% 
  detailed_entries(
    what = What,
    when = When,
    with = With,
    where = Where,
    # why = Why,
    .protect = FALSE
  )
```

# Publications

\bigskip

```{r pubs, results='asis'}
zotero_get_pubs(type = c("journalArticle", "bookSection"))
```


# Software

\bigskip

```{r software, results='asis'}
zotero_get_pubs("computerProgram")
```


# Teaching Experience

```{=html}
<!--# Teaching Interests
A sentence or two about the sorts of courses I'd like to teach.  Tailor to each job application
-->
```

<!--TODO: update this to include workshop series or other workshops-->

```{r}
jobs %>%
  filter(Tag == "teaching", year(Start) > 2005) %>%
  arrange(desc(Start)) %>% 
  detailed_entries(
    what = What,
    when = When,
    with = With,
    where = Where,
    # why = Why, 
    .protect = FALSE)
```
  
## Guest Lectures

```{r}
presentations %>% 
  filter(Tag %in% c("lecture")) %>% 
  arrange(desc(When)) %>% 
  detailed_entries(what = Title,
                   when = glue("{month(When, label = TRUE)} {year(When)}") %>% as.character(),
                   with = Conference,
                   where = Location,
                   why = Award)
```

<!--
# Mentoring Experience

  -	Ellie McDaniel (UF class of 2024) was a summer REU student working on the statistical assumptions and data limitations of applying distributed lag non-linear models to plant demographic analyses.
  -	Andrew Mercadante (UF class of 2022) was a summer REU student working on edge effects in fragmented tropical forests.
  -	Ji-Peng Wei (Masters student at Tea Research Institute) collaborated on four papers with me and was an integral collaborator for most of my PhD work. He went on to work in the tea industry China.
  -	Ming-Ming Guo (Zhejiang University class of 2018) helped carry out field experiments in China in 2018 and co-authored a publication. Ming-Ming was accepted into a PhD program at the Tea Research Institute in Hangzhou, China.
  -	Amma Agyei (Tufts class of 2022) conducted chemical analyses on tea samples and co-authored a publication. She was accepted to a combined BS/MS program in biomedical engineering at Tufts.
  -	Lan Ngo (Tufts class of 2018) piloted a research project to look for indirect effects of climate change in a microbially ripened tea product. She was hired as a Research Data Specialist at Dana-Farber Cancer Institute.
  -	Gabriel Taylor (Tufts class of 2018) accompanied me to China in 2017 to assist with fieldwork. After graduation, he worked for a labor union doing contract enforcement.
  -	Michelle Mu (Tufts class of 2018) piloted a machine learning method for detection of leafhopper damage in leaf scans. She went on to receive a MS from Northeastern and work as a research associate for a biotech firm.
-->

# Grants

```{r}
awards %>%
  filter(tag == "grant") %>%
  detailed_entries(what = award, when = glue("{month(date, label = TRUE)} {year(date)}"),
                   why = amount) %>% 
  mutate(across(everything(), as.character)) %>% 
  mutate(with = as.character(with),
         when = as.character(when),
         where = as.character(where))
```

# Awards and Honors

```{r}
 awards %>% 
  filter(!tag %in% c("failed", "travel", "grant")) %>% 
  brief_entries(what = award, 
                when = glue("{month(date, label = TRUE)} {year(date)}"),
                with = with)
```



# Presentations

## Research Talks

```{r}
presentations %>%
  filter(Tag %in% c("talk", "invited")) %>%
  arrange(desc(When)) %>%
  detailed_entries(what = Title,
                   when = glue("{month(When, label = TRUE)} {year(When)}"),
                   with = Conference,
                   where = Location,
                   why = Award,
                   .protect = FALSE)
```

## Posters

```{r}
presentations %>% 
  filter(Tag == "poster") %>% 
  arrange(desc(When)) %>% 
  detailed_entries(what = Title,
                   when = glue("{month(When, label = TRUE)} {year(When)}"),
                   with = Conference,
                   where = Location,
                   why = Award,
                   .protect = FALSE)
```

# Professional Development

```{r}
development %>% 
  filter(str_detect(tag, "teaching") | str_detect(tag, "dei") | str_detect(tag, "mentoring")) %>% 
  arrange(desc(date)) %>% 
  brief_entries(
    what = title,
    when = glue("{month(date, label = TRUE)} {year(date)}"),
    with = location,
    .protect = FALSE
  )
```

# Outreach

```{r}
outreach %>%
  arrange(desc(sortdate)) %>%
  detailed_entries(when = When,
                   what = Title,
                   with = Organization,
                   where = Location,
                   why = Description)
```

# Service

**Manuscript Reviews**:

```{r results='asis'}
reviews |> 
  glue::glue_data("{Journal} ({Count})") |> 
  glue::glue_collapse(sep = ", ")
```


\bigskip

```{r}
jobs %>%
  filter(Tag == "service") %>% 
  group_by(What) %>% 
  summarize(across(c(When, With, End), first)) %>% 
  arrange(desc(End)) %>% 
    brief_entries(
      what = What,
      when = When,
      with = With
    )
```

<!-- ## Presented Workshops -->

```{r eval=FALSE, include=FALSE}
presentations %>% 
  filter(Tag == "workshop") %>% 
  arrange(desc(When)) %>% 
  brief_entries(
    what = Title,
    when = glue("{month(When, label = TRUE)} {year(When)}"),
    with = Conference,
    # where = Location,
    # why = Award
  )
```

